cs_go_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.home_page_view, name='home_page'),  # Главная страница
    path('raskidki/<slug:map_name>/', views.places_on_the_map_view, name='detail_grenads'),
    # Место раскидки на карте
    path('raskidki/<slug:map_name>/<slug:place>/', views.grenades_list_view, name='place_detail'),  # Список раскидок
    path('raskidki/<slug:map_name>/<slug:place>/<slug:title_slug>/', views.grenade_detail_view,
         name='grenade_detail_correct'),  # Конкретная раскидка
    path('about/', views.about_us_view, name='about_us'),  # Страница о нас
    path('contacts/', views.ContactFormView.as_view(), name='contacts'),  # Форма обратной связи(пока не доделал)
    path('comments/<int:id>/', views.AddCommentsView.as_view(), name='add_comments'),  # Комментарии
    # '''path('add-rating/', views.AddStarRating.as_view(), name='add_rating'),'''  # Добавление рейтинга

]

mainapp/models.py
from django.db import models
from django.urls import reverse
from django.core.files.uploadedfile import InMemoryUploadedFile
from PIL import Image
import sys
from io import BytesIO


def get_product_url(obj, viewname):
    """Функция для навигации по урлам"""

    return reverse(viewname, kwargs={'map_name': obj.map.slug, 'place': obj.place_on_map.slug, 'title_slug': obj.slug})


class Category(models.Model):
    """Класс модели базы данных для категорий"""

    name = models.CharField(max_length=96, verbose_name='Имя категория')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'


class MapCsGo(models.Model):
    """Класс модели базы данных для карт"""

    name = models.CharField(max_length=96, verbose_name='Карта')
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, verbose_name='Категория', max_length=128,
                                 on_delete=models.CASCADE)  # blank=True, null=True

    def __str__(self):
        return f'{self.name}'

    # Название во мн.ч и ед.ч в админки
    class Meta:
        verbose_name_plural = 'Карты'
        verbose_name = 'Карта'

    def get_url(self):
        return reverse('detail_grenads', args=(self.slug,))


class Place(models.Model):
    """Класс модели базы данных для мест на карте(плентов)"""

    name = models.CharField(max_length=64, verbose_name='Место на карте')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name_plural = 'Места на карте'
        verbose_name = 'Место на карте'

    def get_url(self):
        return reverse('place_detail', kwargs={"place": self.slug})  # place_detail


# название класса сменить на более подходящее
class Content(models.Model):
    """Класс модели базы данных для раскидок"""

    MIN_RESOLUTION = (450, 300)
    MAX_RESOLUTION = (451, 301)
    MAX_IMAGE_SIZE = 3145728

    EAZY = 'Легкая'
    OKAY = 'Средняя'
    HARD = 'Продвинутая'

    DIFFICULTY_CHOISE_FIELD = [
        (EAZY, 'Легкая'),
        (OKAY, 'Средняя'),
        (HARD, 'Продвинутая'),
    ]

    category = models.ForeignKey(Category, verbose_name='Категория', max_length=128, on_delete=models.CASCADE)
    map = models.ForeignKey(MapCsGo, max_length=128, verbose_name='Карта', on_delete=models.CASCADE)
    place_on_map = models.ForeignKey(Place, verbose_name='Место на карте', on_delete=models.CASCADE,
                                     max_length=128)
    difficulty = models.CharField(choices=DIFFICULTY_CHOISE_FIELD, verbose_name='Сложность броска', null=True,
                                  blank=True, max_length=12)
    title = models.CharField(max_length=128, verbose_name='Название раскидки')
    slug = models.SlugField(unique=True)
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(verbose_name='Изображение карты', blank=True, null=True)
    video = models.FileField(verbose_name='Видео')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name_plural = 'Раскидки'
        verbose_name = 'Раскидка'

    def get_url(self):
        return get_product_url(self, 'grenade_detail_correct')

    def save(self, *args, **kwargs):
        """Метод по обрезанию изображения миниатюры в админке"""

        image = self.image
        img = Image.open(image)
        new_img = img.convert('RGB')
        resized_new_img = new_img.resize((450, 300), Image.ANTIALIAS)
        filestream = BytesIO()
        resized_new_img.save(filestream, 'JPEG', quality=90)
        filestream.seek(0)
        img_name = '{}.{}'.format(*self.image.name.split('.'))
        self.image = InMemoryUploadedFile(
            filestream, 'ImageField', img_name, 'jpeg/image', sys.getsizeof(filestream), None
        )

        super().save(*args, **kwargs)


class Comments(models.Model):
    """Класс модели базы данных для комментариев"""

    email = models.EmailField(max_length=96)
    name = models.CharField(max_length=48, verbose_name='Имя')
    text = models.TextField(max_length=1000, verbose_name='Сообщение')
    parents = models.ForeignKey('self', verbose_name='Родители', on_delete=models.SET_NULL, blank=True, null=True)
    grenade = models.ForeignKey(Content, verbose_name='Раскидка', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.grenade}'

    class Meta:
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'


'''
class RatingStart(models.Model):
    value = models.PositiveSmallIntegerField(verbose_name='Значение', default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name_plural = 'Звезды рейтинга'
        verbose_name = 'Звезда рейтинга'
        ordering = ['-value']


class Rating(models.Model):
    ip = models.CharField(verbose_name='IP address', max_length=15)
    star = models.ForeignKey(RatingStart, on_delete=models.CASCADE, verbose_name='Звезды')
    grenade = models.ForeignKey(Content, on_delete=models.CASCADE, verbose_name='Раскидка')

    def __str__(self):
        return f'{self.star} - {self.grenade}'

    class Meta:
        verbose_name_plural = 'Рейтинги'
        verbose_name = 'Рейтинг'
'''

mainapp/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import Comments


class ContactForm(forms.Form):
    """Форма для обратной связи(сырая)..
        учился работать с самой простой капчей"""
    name = forms.CharField(max_length=64, label='Имя')
    email = forms.EmailField(max_length=96, label='Email')
    text = forms.CharField(widget=forms.Textarea(attrs={'cols': 60, 'rows': 10}))
    captcha = CaptchaField()


class CommentsForm(forms.ModelForm):
    """Форма для добавления комментариев"""
    class Meta:
        model = Comments
        fields = ('name', 'email', 'text')

# class RatingForm(forms.ModelForm):

# star = forms.ModelChoiceField(
# queryset=RatingStart.objects.all(), widget=forms.RadioSelect(), empty_label=None
# )

# class Meta:
# model = Rating
# fields = ('star',)

mainapp/views.py
from django.shortcuts import (render, redirect)
from django.views import View
from django.views.generic import FormView
from django.urls import reverse_lazy
from .forms import (ContactForm, CommentsForm)
from .models import (Content, MapCsGo, Place)


def home_page_view(request): # Home_page_view
    """Функция представления главной страницы"""

    maps = MapCsGo.objects.all()
    context = {
        'maps': maps,
    }

    return render(request, 'mainapp/base.html', context=context)


def places_on_the_map_view(request, map_name, *args, **kwargs):
    """Функция представления возвращающая страницу
        с местами раскидки на карте"""

    grenades = Content.objects.all().filter(map__slug=map_name)
    places = Place.objects.all()
    context = {
        'grenades': grenades,
        'map_name': map_name,
        'places': places,
    }

    return render(request, 'mainapp/detail_category.html', context=context)


def grenades_list_view(request, map_name: str, place: str):
    """Функция представления возвращающая страницу
        с списком раскидок"""

    grenades = Content.objects.all().filter(place_on_map__slug=place).filter(map__slug=map_name)
    context = {
        'grenades': grenades,
        'map_name': map_name,
        'place': place,
    }
    return render(request, 'mainapp/place_detail.html', context=context)


# обратная связь не готово
def about_us_view(request):
    """Функция не готова, пока заморожена"""
    return render(request, 'mainapp/about_us.html')


class ContactFormView(FormView):
    """Класс представления обратной связи,
        тестово, пока заморожено"""

    form_class = ContactForm
    template_name = 'contacts.html'
    success_url = reverse_lazy('home_page')

    def form_is_valid(self, form):
        return redirect('home_page')


# комменты
class AddCommentsView(View):
    """Класс представления для добавления
        комментариев к раскидкам"""

    def post(self, request, id):
        form = CommentsForm(request.POST)
        grenade = Content.objects.get(id=id)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parents_id = int(request.POST.get("parent"))
            form.grenade = grenade
            form.save()
        return redirect(grenade.get_url())


'''class AddStarRating(View):

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(','[0])
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):

        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                grenade_id=int(request.POST.get('grenade')),
                defaults={'star_id': int(request.POST.get('star'))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)
'''


def grenade_detail_view(request, map_name: str, place: str, title_slug: str):
    """Функция представления возвращающая страницу
        с подробной информацией о раскидке"""

    grenade = Content.objects.all().filter(slug=title_slug)
    context = {
        'grenades': grenade,
        'map_name': map_name,
        'place': place,
        'title_slug': title_slug,
    }
    return render(request, 'mainapp/grenade_detail.html', context=context)

mainapp/templates/mainapp/about_us.html
{% extends 'mainapp/base.html' %}

{% block title %} О нас{% endblock title %}

{% block content %}

    <h2>О нас</h2>

    <p>Любители кс го</p>

{% endblock content %}

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}CS-GO раскидки{% endblock title %}</title>
</head>
<body>

    <h1><a href="/">Home</a></h1>
    <h1><a href="{% url 'about_us' %}">О нас</a></h1>

    {% block content %}
        <h2>Карты</h2>
        <ul>
            {% for map in maps %}
                <li><a href="{{ map.get_url }}">{{ map.name }}</a></li>
            {% endfor %}
        </ul>
    {% endblock content %}
</body>
</html>

mainapp/templates/mainapp/detail_category.html
{% extends 'mainapp/base.html' %}

{% block title %}Положение на карте{% endblock title %}

{% block content %}

    <h2>Место раскидки</h2>

    {% for place in places %}
        <p><a href="{{ place.slug }}">{{ place.name }}</a></p>
    {% endfor %}

{% endblock content %}

mainapp/templates/mainapp/grenade_detail.html
{% extends 'mainapp/base.html' %}
{% block title %}
    {% for grenade in grenades %}
        {{ grenade.title }}
    {% endfor %}
{% endblock title %}

{% block content %}
    {% for grenade in grenades %}
        <p>{{ grenade.title }}</p>
        <p>{{ grenade.description }} ОПИСАНИЕ ОПИСАНИЕ НЕ БАГ</p>
        <img src="{{ grenade.image.url }}" alt="{{ grenade.image }}" width="650px" height="400">


        <video controls width="650px" height="400">
            <source src="{{ grenade.video.url }}" >
        </video>



    <form action="{% url 'add_comments' grenade.id %}" method="post" id="formComments">
             {% csrf_token %}

             <input type="hidden" name="parent" id="contactparent" value="">

             <div>
                <label for="contactcomments">Ваш комментарий</label>
                <textarea name="text" id="contactcomments" cols="25" rows="7" required=""></textarea>
             </div>

             <div>
                <label for="contactusername">Имя</label>
                <input type="text" name="name" id="contactusername">
            </div>

            <div>
                <label for="contactemail">Email</label>
                <input type="text" name="email" id="contactemail">
            </div>

            <button type="submit">Опубликовать</button>

        </form>

        {% for comment in grenade.comments_set.all %}
            <p>Имя - {{ comment.name }}</p>
            <p >Комментарий:</p>
            <p style="padding-left: 15px">{{ comment.text }}</p>
            <a href="#formComments" onclick="addComments('{{ comment.name }}', '{{ comment.id }}')">Ответить..</a>
        {% endfor %}

    {% endfor %}
    <script type="text/javascript">
        function addComments(name, id) {
            document.getElementById("contactparent").value = id;
            document.getElementById("contactcomments").innerText = `${name}, `
        }
    </script>
{% endblock content %}

mainapp/templates/mainapp/place_detail.html
{% extends 'mainapp/base.html' %}

{% block title %}{{ place.title }} {% endblock title %}

{% block content %}

    <h2>Раскидки для {{ map_name }} {{ place }} </h2>
    <ul>
        {% for grenade in grenades %}
        <li><a href="{{ grenade.get_url }}">{{ grenade.title }}</a></li>
    {% endfor %}
    </ul>



{% endblock content %}